### ISSUE TITLE
Possible to upload the S3D pretrained weights somewhere other than Baidu

### ISSUE THREAD

**Issue by nlml** [antoine77340/S3D_HowTo100M#1]
Hi there

Thanks for this great repo.

It seems to be impossible for me to download the weights from Baidu without a Chinese number. Could you possibly upload the RGB weights somewhere else? Even to a separate github repo should be fine as they are only 50mb?

Thanks
Liam

**Comment by antoine77340** [comment]
Hi,

I am not sure to understand why you cannot download the models since there are not hosted on Baidu, what about from:
https://www.di.ens.fr/~miech/S3D_howto100m/s3d_dict.npy
https://www.di.ens.fr/~miech/S3D_howto100m/s3d_howto100m.pth

?

**Comment by nlml** [comment]
Oh, how embarassing. I meant to open this issue on a different repo - https://github.com/qijiezhao/s3d.pytorch

Thank you for your work as well :)
