### ISSUE TITLE
Question in Sentence Embedding

### ISSUE THREAD

**Issue by JoanFM** [antoine77340/S3D_HowTo100M#13]
I have a question about the Sentence_Embedding model forward implementation.

Why is torch max applied after the first Fully Conbected layer? Is this better than doing it before and averaging all the word embeddings of a sentence before the FC Layers?

Thanks for the clarification

**Comment by antoine77340** [comment]
Yes it was better to do the max than the average.

**Comment by JoanFM** [comment]
Thanks!
