### ISSUE TITLE
Video preprocessing steps?

### ISSUE THREAD

**Issue by yushuinanrong** [antoine77340/S3D_HowTo100M#5]
Hi @antoine77340,

Thanks for sharing this codebase. I'd like to evaluate your pretrained model on several custom videos but I don't see any code/instruction on how to preprocess the videos for inference. Could you share some insight?

Thanks,

**Comment by antoine77340** [comment]
Hi,

You can take a look at our end-to-end evaluation script on YouCook2: https://github.com/antoine77340/MIL-NCE_HowTo100M/blob/master/eval_youcook.py

Or HMDB:  https://github.com/antoine77340/MIL-NCE_HowTo100M/blob/master/eval_hmdb.py

**Comment by yushuinanrong** [comment]
@antoine77340 
Thanks for your reply. Based on this line:
https://github.com/antoine77340/MIL-NCE_HowTo100M/blob/dd0ff324439fed58de6a4ffc50f3d582a22cc2a4/eval_youcook.py#L63
it seems preprocessing only need to rescale the pixel value to [0, 1], is it right?

**Comment by antoine77340** [comment]
That's right!

**Comment by yushuinanrong** [comment]
@antoine77340 
Could you help to confirm the pretrained S3D model in this codebase is same as the one you generating the public available features for Howto100M (https://www.di.ens.fr/willow/research/howto100m/)?
