### ISSUE TITLE
space_to_depth value

### ISSUE THREAD

**Issue by thematrixduo** [antoine77340/S3D_HowTo100M#6]
In this repository 'space_to_depth' is set to True in S3D model. However in the training repository (https://github.com/antoine77340/MIL-NCE_HowTo100M/blob/) 'space_to_depth' is set to False. Could you confirm if this is intentionally set differently? Thanks!

**Comment by antoine77340** [comment]
Yes it is intentional.
space_to_depth was set to True here so we could load the weights we have trained using TPUs.
This trick is useful to speedup the training process on TPU.

However, if you train on GPU, you will not need this space_to_depth trick.

**Comment by thematrixduo** [comment]
Got it, Thanks for the prompt reply!
